baseurl = "/"
languageCode = "es-cl"
title = "Bicameral"
theme = "hugo-lithium"
googleAnalytics = "UA-152402500-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Acerca de"
    url  = "/about/"
[[menu.main]]
    name = "Twitter"
    url  = "https://twitter.com/Bicameral_CL"
[[menu.main]]
    name = "Spotify"
    url  = "https://open.spotify.com/show/7eL0L2zmrZA9BoSv2zXdzD"
[[menu.main]]
    name = "Apple Podcast"
    url  = "https://podcasts.apple.com/gb/podcast/bicameral/id1471447826"
[[menu.main]]
    name = "Google Podcast"
    url  = "https://podcasts.google.com/?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy9jNzcwMjcwL3BvZGNhc3QvcnNz"

[params]
    description = "Bicameral, el podcast de discusión y análisis de los eventos legislativos en Chile."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

